on:
  workflow_dispatch:
  push:
    branches:
    - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  atualiza_o_readme:
    name: Atualiza o README.md
    runs-on: ubuntu-latest

    steps:
    - name: Faz o clone do repositorio na maquina do GHA
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install libcurl4-openssl-dev
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tinytex: true 
    
    # - name: carrega pacotes do renv
    
    - name: Render README and Commit Results
      run: |
        Rscript -e 'install.packages("webshot2", repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/noble/latest"))'
        Rscript -e 'install.packages("rmarkdown", repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/noble/latest"))'
        Rscript -e 'install.packages("tidyverse", repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/noble/latest"))'
        Rscript -e 'install.packages("sparklyr", repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/noble/latest"))'
        Rscript -e 'install.packages("pysparklyr", repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/noble/latest"))'
        Rscript -e 'install.packages("knitr", repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/noble/latest"))'
        Rscript -e 'install.packages("plotly", repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/noble/latest"))'
        Rscript -e 'install.packages("rmarkdown", repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/noble/latest"))'
        quarto render README.qmd
        git config --local user.name "$GITHUB_ACTOR"
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git commit README.md -m 'Re-build Rmarkdown files' || echo "No changes to commit"
        git push origin || echo "No changes to commit"

    # - name: atualiza o README.md
    # - run: ...
  
    # - name: sobe o README.md atualizado no repositorio
    # - run: ...
